apiVersion: v1
kind: PersistentVolume
metadata:
  name: mirrormaker1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  hostPath:
    path: /home/ubuntu/mount   # Adjust the host path as needed

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirrormaker1-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
  volumeName: mirrormaker1-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirrormaker2-1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirrormaker1-pod
  template:
    metadata:
      labels:
        app: mirrormaker1-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: lke.linode.com/pool-id
                operator: In
                values: 
                - "233625"
      containers:
      - name: ubuntu-container
        image: 123456devops/mirrorpod:v2
        command: ["/bin/bash", "-c"]
        args:
        - "while true; do sleep 3600; done"
        volumeMounts:
        - name: data-volume
          mountPath: /home/ubuntu/kafka  # Mount path inside the container
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mirrormaker1-data
